/**
 * Awash Bank parser.
 *
 * Endpoint: https://awashpay.awashbank.com:8225/-{shareToken}
 * Response: HTML receipt page with table-based layout
 *
 * The receipt URL uses a share token (e.g. 2KDL95Z0NR-4U61O6) generated by the
 * Awash app. The visible numeric Transaction ID on the mobile receipt is NOT the
 * same token and cannot be used directly. Users must paste the share URL.
 *
 * SSL verification is disabled because the endpoint uses a self-signed or
 * otherwise non-publicly-trusted certificate on port 8225.
 */
import * as https from "node:https";
import { BaseParser } from "./base.js";
import type { ParsedReceipt, Result, HttpResult } from "../core/types.js";
import { ok, err } from "../core/types.js";

const BROWSER_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36";

function htmlToText(html: string): string[] {
  return html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, "\n")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

function findValue(lines: string[], label: string, startIndex = 0): string | undefined {
  const lowerLabel = label.toLowerCase();

  // First pass: prefer exact label lines (label only or label + colon/equals).
  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if (line === lowerLabel || line === `${lowerLabel}:` || line === `${lowerLabel}=`) {
      // Same line: value is on the next line(s)
      if (i + 1 < lines.length) {
        let j = i + 1;
        if (lines[j] === ":" && j + 1 < lines.length) j++;
        return lines[j];
      }
    }
  }

  // Second pass: accept a line containing the label followed by a delimiter and value.
  for (let i = startIndex; i < lines.length; i++) {
    if (lines[i].toLowerCase().includes(lowerLabel)) {
      const sameLineMatch = lines[i].match(new RegExp(`${label}\\s*[:=]\\s*(.+)$`, "i"));
      if (sameLineMatch) return sameLineMatch[1].trim();
    }
  }

  // Third pass: accept a line containing the label and a value on the next line.
  // Skip common compound labels like "Merchant Payment" when looking for "Merchant".
  for (let i = startIndex; i < lines.length; i++) {
    if (lines[i].toLowerCase().includes(lowerLabel)) {
      // Reject compound lines where the label is followed by other words without a delimiter
      const remainder = lines[i].replace(new RegExp(`^.*?${label}`, "i"), "").trim().toLowerCase();
      if (remainder && !remainder.startsWith(":")) continue;

      if (i + 1 < lines.length) {
        let j = i + 1;
        if (lines[j] === ":" && j + 1 < lines.length) j++;
        return lines[j];
      }
    }
  }

  return undefined;
}

function findValueAfterAll(labels: string[], lines: string[]): string | undefined {
  for (let start = 0; start < lines.length; start++) {
    if (labels.every((l) => lines.slice(start).some((line) => line.toLowerCase().includes(l.toLowerCase())))) {
      // All labels exist after start; find the last one and return its value
      let idx = start;
      for (const label of labels) {
        for (let i = idx; i < lines.length; i++) {
          if (lines[i].toLowerCase().includes(label.toLowerCase())) {
            idx = i;
            break;
          }
        }
      }
      return findValue(lines, labels[labels.length - 1], idx);
    }
  }
  return undefined;
}

export class AwashParser extends BaseParser {
  readonly bankId = "awash";
  readonly bankName = "Awash Bank";
  readonly responseType = "html" as const;
  readonly requiresAccount = false;
  readonly accountDigits?: number = undefined;
  readonly requiresPhone = false;
  readonly sslVerify = false;

  buildUrl(ref: string, _account?: string, _phone?: string): string {
    return `https://awashpay.awashbank.com:8225/-${ref}`;
  }

  /**
   * Override fetch to disable SSL verification for the Awash endpoint.
   */
  async fetchReceipt(
    ref: string,
    account?: string,
    phone?: string,
    options?: { fallbackUrl?: string }
  ): Promise<Result<HttpResult>> {
    const url = this.buildUrl(ref, account, phone);

    for (let attempt = 0; attempt <= 2; attempt++) {
      try {
        const data = await new Promise<string>((resolve, reject) => {
          const req = https.get(
            url,
            {
              headers: { "User-Agent": BROWSER_UA, Accept: "text/html,*/*" },
              rejectUnauthorized: false,
              timeout: 15000,
            },
            (res) => {
              let chunks = "";
              res.on("data", (c) => (chunks += c.toString()));
              res.on("end", () => resolve(chunks));
            }
          );
          req.on("error", reject);
          req.on("timeout", () => req.destroy(new Error("timeout")));
        });

        const contentType = "text/html";
        return ok({ status: 200, data, contentType });
      } catch (e) {
        if (attempt === 2) {
          return err({
            kind: "ENDPOINT_ERROR" as const,
            bank: this.bankName,
            message: `Failed to reach Awash: ${e instanceof Error ? e.message : String(e)}`,
            fallbackUrl: options?.fallbackUrl,
          });
        }
        await new Promise((r) => setTimeout(r, 1000 * Math.pow(2, attempt)));
      }
    }

    return err({
      kind: "ENDPOINT_ERROR" as const,
      bank: this.bankName,
      message: "Failed to reach Awash after 3 attempts.",
    });
  }

  parse(data: string | Buffer, _contentType: string): ParsedReceipt {
    const raw = data.toString();

    if (raw.includes("Invalid receipt id") || raw.toLowerCase().includes("invalid receipt")) {
      return { verified: false, raw: raw.slice(0, 500) };
    }

    const lines = htmlToText(raw);
    const text = lines.join("\n");

    // Sender info can appear under "Customer Name" in the company section
    // or explicitly under "Sender Name" in the transaction section.
    const senderName = findValue(lines, "Sender Name") || findValue(lines, "Customer Name");
    const senderAccount =
      findValue(lines, "Sender Account") ||
      findValue(lines, "Source Account") ||
      findValue(lines, "Account No");

    // Receiver info varies by transaction type:
    // - Send To Bank / Send Money: Receiver Name / Receiver Account
    // - IPS Bank Transfer: Beneficiary name / Beneficiary Account
    // - Merchant Payment: Merchant / Till Number (recipient is the merchant)
    // - Telebirr Transfer: Phone Number only (no receiver name or account)
    const receiverName =
      findValue(lines, "Receiver Name") ||
      findValue(lines, "Beneficiary name") ||
      findValue(lines, "Merchant") ||
      findValue(lines, "Recipient");
    const receiverAccount =
      findValue(lines, "Receiver Account") ||
      findValue(lines, "Beneficiary Account") ||
      findValue(lines, "Till Number") ||
      findValue(lines, "Recipient") ||
      findValue(lines, "Phone Number");

    const reason = findValue(lines, "Reason");
    const transactionType =
      findValue(lines, "Transaction Type") || findValue(lines, "Transaction type");
    const branch = findValue(lines, "Branch");
    const transactionId = findValue(lines, "Transaction ID");

    const date = findValue(lines, "Transaction Date") || findValue(lines, "Transaction Time");

    let amount: number | undefined;
    const amountStr = findValue(lines, "Amount");
    if (amountStr) {
      const m = amountStr.replace(/,/g, "").match(/(\d+(?:\.\d+)?)/);
      if (m) amount = parseFloat(m[1]);
    }

    const verified =
      !!senderName &&
      !!senderAccount &&
      (!!receiverName || !!receiverAccount) &&
      amount !== undefined &&
      !!date;

    return {
      verified,
      reference: transactionId,
      senderName,
      senderAccount,
      receiverName,
      receiverAccount,
      amount,
      currency: "ETB",
      date,
      branch,
      reason,
      transactionType,
      raw: text.slice(0, 1500),
    };
  }
}
